###pandas Overview
pands is a powerful python library for manipulation and analysis. it provides two primary data structures: Series and Dataframe
Installation: You can install Panda using pip:

pip install pandas

###Series
 Series ia one dimensional lebeled array capable of holdin any type of data type. It is similar to one dimensional Numpy array but with additional funtionality and labeled index.

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
#code example
import pandas as pd
#creating a series from a python list
s= pd.Series([1,2,3,'angel',4,5])
print(s)

0        1
1        2
2        3
3    angel
4        4
5        5
dtype: object

##DataFrame
DataFrame is 2 dimensional data structure with column of potentially diffent data types. It is similar to a spreadsheet or SQL table

In [8]:
df={'name':["David","sarah","moses"],
   'age':[59,20,33],
  'location':['boston','adenta','columbus']
   }
data=pd.DataFrame(df)
print(data)

    name  age  location
0  David   59    boston
1  sarah   20    adenta
2  moses   33  columbus

In [50]:
#code example:
#creating a dataframe from a dictionary
data={'name':['john','alice','Bod'],
      'age':[30,25,35],
      'city':['newyork','paris','london']}
df=pd.DataFrame(data)
print(df)

    name  age     city
0   john   30  newyork
1  alice   25    paris
2    Bod   35   london

##Data Manipulation
Indexing and slicing:you can access and manipulate data in sries and DataFrame using and slicing.

In [10]:
#Accessing elements in a series
print(s[0]) # Accessing the first element

#slicing a DataFrame
df[['name']] #Accessing a column

1

    name
0   john
1  alice
2    Bod

In [11]:
x={'name':['john','alice','Bod'],
      'age':[30,25,35],
      'city':['newyork','paris','london']}
df= pd.DataFrame(x)
print(df)
#slicing a DataFrame

df[['name']] #Accessing a column

    name  age     city
0   john   30  newyork
1  alice   25    paris
2    Bod   35   london

    name
0   john
1  alice
2    Bod

In [12]:
import pandas as pd

s = pd.Series([1,2,3,4,5])

# Accessing elements
print(s[0])
##Accessing elements in a series
print(s[0]) # Accessing the first element

1
1

##Data Combination
 Data combintion is the process of joining,merging or concatenating multiple pandas data structures into a single data structure.
  The most common ways of combine dataframes are concatenation,joining and merge

## Concatenation

using the concat function to combine 2 or more dataframes with the same column either vertically or horizontally.

In [13]:
df_1=pd.DataFrame({'a':[4,2,6],'b':['m','n','o']})
df_2=pd.DataFrame({'a':[45,8,9],'b':['x','y','z']})

In [14]:
df_1

   a  b
0  4  m
1  2  n
2  6  o

In [15]:
df_2

    a  b
0  45  x
1   8  y
2   9  z

In [16]:
#vertical concatenation(row.wise)
vertical_com=pd.concat([df_1,df_2], axis=0, keys=['df_1','df_2'])
vertical_com

         a  b
df_1 0   4  m
     1   2  n
     2   6  o
df_2 0  45  x
     1   8  y
     2   9  z

In [17]:
# Horizontal concatenation is a rowise concatenation.
horizontal_com =pd.concat([df_1,df_2],axis=1,keys=['df_1','df_2'])
horizontal_com

  df_1    df_2
     a  b    a  b
0    4  m   45  x
1    2  n    8  y
2    6  o    9  z

In [18]:
#loc is location
vertical_com.loc['df_1',0]

a    4
b    m
Name: (df_1, 0), dtype: object

In [19]:
vertical_com.loc["df_1",0][0]

/tmp/ipykernel_555/2645724590.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vertical_com.loc["df_1",0][0]

np.int64(4)

In [20]:
vertical_com.loc["df_1",0].iloc[0]

np.int64(4)

In [21]:
vertical_com.loc["df_1",0]["a":"b"]

a    4
b    m
Name: (df_1, 0), dtype: object

In [22]:
#vertical concatenation (row-wise)
vertical_com = pd.concat([df_1,df_2], axis=0,ignore_index=True)
vertical_com

    a  b
0   4  m
1   2  n
2   6  o
3  45  x
4   8  y
5   9  z

In [23]:
Lagos_island=pd.DataFrame({'Town':['Marina','Obalende','Lekki'],
                    'Humidity':[32,29,14],
                    'Temperature':[23,30,25]})
Lagos_mainland= pd.DataFrame({'Town':['Ikotun','Surulere','Yaba'],
                              'Humidity':[27,39,36],
                              'Temperature':[30,26,24]})

In [28]:
df_3=pd.concat([Lagos_island,Lagos_mainland],ignore_index=True)
df_3

       Town  Humidity  Temperature
0    Marina        32           23
1  Obalende        29           30
2     Lekki        14           25
3    Ikotun        27           30
4  Surulere        39           26
5      Yaba        36           24

In [26]:
df_4=pd.DataFrame({'Windspeed':[8,5,7,8,6,4,9,10,5]})
df_4

   Windspeed
0          8
1          5
2          7
3          8
4          6
5          4
6          9
7         10
8          5

In [29]:
df_5=pd.concat([df_3,df_4],axis=1,ignore_index=True)
df_5

          0     1     2   3
0    Marina  32.0  23.0   8
1  Obalende  29.0  30.0   5
2     Lekki  14.0  25.0   7
3    Ikotun  27.0  30.0   8
4  Surulere  39.0  26.0   6
5      Yaba  36.0  24.0   4
6       NaN   NaN   NaN   9
7       NaN   NaN   NaN  10
8       NaN   NaN   NaN   5

In [30]:
df_5=pd.concat([df_3,df_4],ignore_index=True)
df_5

        Town  Humidity  Temperature  Windspeed
0     Marina      32.0         23.0        NaN
1   Obalende      29.0         30.0        NaN
2      Lekki      14.0         25.0        NaN
3     Ikotun      27.0         30.0        NaN
4   Surulere      39.0         26.0        NaN
5       Yaba      36.0         24.0        NaN
6        NaN       NaN          NaN        8.0
7        NaN       NaN          NaN        5.0
8        NaN       NaN          NaN        7.0
9        NaN       NaN          NaN        8.0
10       NaN       NaN          NaN        6.0
11       NaN       NaN          NaN        4.0
12       NaN       NaN          NaN        9.0
13       NaN       NaN          NaN       10.0
14       NaN       NaN          NaN        5.0

The merge function is used to conbine two or more dataframes based on a common column(s)

In [31]:



df_5=pd.DataFrame({'Names':['Ama','Berry','Dela','Tola'],'Score1':[1,2,3,4]})
df_6=pd.DataFrame({'Names':['Berry','Moses','Debby','Dela'],'Score2':[5,6,7,8]})

In [ ]:
df_5

   Names  Score1
0    Ama       1
1  Berry       2
2   Dela       3
3   Tola       4

In [32]:
df_6

   Names  Score2
0  Berry       5
1  Moses       6
2  Debby       7
3   Dela       8

In [33]:
pd.merge(df_5,df_6, on='Names', how='inner')

   Names  Score1  Score2
0  Berry       2       5
1   Dela       3       8

In [ ]:
pd.merge(df_5,df_6, on='Names',how='outer')

   Names  Score1  Score2
0    Ama     1.0     NaN
1  Berry     2.0     5.0
2  Debby     NaN     7.0
3   Dela     3.0     8.0
4  Moses     NaN     6.0
5   Tola     4.0     NaN

In [34]:
pd.merge(df_5,df_6,on='Names',how='left')

   Names  Score1  Score2
0    Ama       1     NaN
1  Berry       2     5.0
2   Dela       3     8.0
3   Tola       4     NaN

In [35]:
pd.merge(df_5,df_6,on='Names',how='right')

   Names  Score1  Score2
0  Berry     2.0       5
1  Moses     NaN       6
2  Debby     NaN       7
3   Dela     3.0       8

In [36]:
# The two dataframeshaving different column names
df_7=pd.DataFrame({'Name1':['Ama','Berry','Celestine','Dela'],'Score':[1,2,3,4]})
df_8=pd.DataFrame({'Name2':['Berry','Dela','Emma','Frank'], 'Score':[5,6,7,8]})
merge_df=pd.merge(df_7,df_8,left_on='Name1',right_on='Name2', how='inner',suffixes=('_df7','_df8'))
merge_df

   Name1  Score_df7  Name2  Score_df8
0  Berry          2  Berry          5
1   Dela          4   Dela          6

The join function id used to combine two dataframes on their indexes

In [37]:


df_9=pd.DataFrame({'Value1':[1,2,3,4]}, index=['A','B','C','D'])
df_10=pd.DataFrame({'Value2':[5,6,7,8]},index=['B','D','E','F'])

In [ ]:
df_9

   Value1
A       1
B       2
C       3
D       4

In [38]:
df_10

   Value2
B       5
D       6
E       7
F       8

In [39]:
df_9.join(df_10, how='inner')

   Value1  Value2
B       2       5
D       4       6

In [40]:
joined=df_9.join(df_10, how='left',lsuffix='_left',rsuffix='_right')
joined

   Value1  Value2
A       1     NaN
B       2     5.0
C       3     NaN
D       4     6.0

Filtering: You can filter data based on condition.

In [42]:
# Filtering rows based on condition
filter_df=df[df['age']>30]
filter_df

  name  age    city
2  Bod   35  london

In [51]:
filter_df2=df[df['name']=='john']
filter_df2

   name  age     city
0  john   30  newyork

Adding and Removing Colums:
 You can add new column to the existing one and also remove column

In [62]:
#Code example
#Creating a DataFrame frpm a dictionary
data={'Name':['John', 'Alice', 'Bob'],
       'Age':[30,25,35],
       'City':['Newyork','Paris','London']}

df=pd.DataFrame(data)
df

    Name  Age     City
0   John   30  Newyork
1  Alice   25    Paris
2    Bob   35   London

In [63]:
#Adding a new column
df['Gender']=['Male','Female','Male']


print(df)

    Name  Age     City  Gender
0   John   30  Newyork    Male
1  Alice   25    Paris  Female
2    Bob   35   London    Male

In [64]:
#Removing a column
df.drop('City', axis=1,inplace=True)
df

    Name  Age  Gender
0   John   30    Male
1  Alice   25  Female
2    Bob   35    Male

Grouping and aggregation

You can group data based on one or more columns and perform aggregation functions.

In [65]:
# Creating a Dataframe from a dictionary
data={'Num':[10,20,30],
      'Age':[10,25,35],
      'val':[50,60,70]}
df=pd.DataFrame(data)
df

   Num  Age  val
0   10   10   50
1   20   25   60
2   30   35   70

In [68]:
group_df=df.groupby('Age')
group_df

In [69]:
group_df=df.groupby('Age').mean()
group_df

      Num   val
Age
10   10.0  50.0
25   20.0  60.0
35   30.0  70.0

In [70]:
group_df=df.groupby('Age').max()
group_df

     Num  val
Age
10    10   50
25    20   60
35    30   70

Handling Missing Data:
Panda provides methods for handling missing data, such as dropping or filling missing values.
3 Example:
Dropping rows with missing values
cleaned_df=df.dropna()
Filing missing values with a specified value

filed_df=df.fillna(0)

In [73]:
#Creating a dataframe from a dictionary
data={'A':[1,2,None,4],
      'B':[None,5,6,7]}
df=pd.DataFrame(data)
#Check missing values
print(df.isnull())

       A      B
0  False   True
1  False  False
2   True  False
3  False  False

Reading files with Pandas:

Import pandas:
Import the pandas library in your python script or jupyter Notebook.
Import pandas as pd
Readin CSV files:
Use the read_csv() function to read from the CSV(Comma-seperated Values) file.
Syntax
df=pd.read_csv('filename.csv')
options:
sep: Specifies the delimeter(default is,).
header:Specifies the row number to use as column names.
index_col:Specifies the column to use as the row index.
usecols: Specifies a subset of column to read.

In [74]:
import pandas as pd
# Reading CSV FILE WITH A DIFFERENT DELIMETER
df1 = pd.read_csv('sample_data.csv', sep=',')
print(df1.head())  # Displaying the first few rows of the DataFrame

    Name  Age           City
0   John   30       New York
1  Alice   25    Los Angeles
2    Bob   35        Chicago
3  Emily   28        Houston
4  David   32  San Francisco

In [75]:
import pandas as pd

# File path of the Excel file
excel_file_path = "/content/sample_data_excel.xlsx"

# Read the Excel file using pandas
df = pd.read_excel(excel_file_path,
                   header=0,  # Use the first row as column names
                   index_col=None,  # Do not use any column as index
                   usecols=None  # Read all columns
                   )

# Display the DataFrame
print(df)

         Name  Age            City
0        John   30        New York
1       Alice   25     Los Angeles
2         Bob   35         Chicago
3       Emily   28         Houston
4       David   32   San Francisco
5     Michael   27           Miami
6       Sarah   40         Seattle
7      Daniel   33          Boston
8        Emma   29          Dallas
9       James   45         Phoenix
10     Olivia   31    Philadelphia
11    William   22       San Diego
12     Sophia   37          Austin
13  Alexander   26          Denver
14        Ava   39        Portland
15      Ethan   34         Atlanta
16        Mia   24       Charlotte
17    Michael   41         Detroit
18   Isabella   28     San Antonio
19   Benjamin   36       Las Vegas
20  Charlotte   32       Nashville
21    Matthew   29     Minneapolis
22     Amelia   38         Orlando
23      Lucas   23  Salt Lake City
24     Harper   42     Kansas City
25      Henry   30    Indianapolis
26     Evelyn   35         Raleigh
27    Jackson   27        Columbus
28       Liam   33       Milwaukee
29    Abigail   26          Tucson

In [76]:
df.head()

    Name  Age           City
0   John   30       New York
1  Alice   25    Los Angeles
2    Bob   35        Chicago
3  Emily   28        Houston
4  David   32  San Francisco

In [77]:
df.tail()

       Name  Age          City
25    Henry   30  Indianapolis
26   Evelyn   35       Raleigh
27  Jackson   27      Columbus
28     Liam   33     Milwaukee
29  Abigail   26        Tucson